### PR TITLE
implemented several features

### PR DESCRIPTION
**Pull request by aash**
See the log for detailed description.

### CODE REVIEW

**Comment by henricavalcante** [comment]
what we need to merge it?

**Comment by aash** [comment]
@henricavalcante 
Hi. HighVoltz' approval for the pull request.

**Comment by henricavalcante** [comment]
I'm just being sarcastic.

This pull request was opened more than 2 months ago.

**Comment by aash** [comment]
I believe sarcasm is inappropriate here because this is not paid product, it is free, so give some credit. HighVoltz can do whatever he wants to do, including stopping to support it. If your intention was to complain or force pull request process you should do it in respectful manner. Sorry if it sound offensive. I just want this conversation be constructive.

**Comment by henricavalcante** [comment]
Sorry, I'm just kidding.

**Comment by henricavalcante** [comment]
just a tip: But if you create distinct branches for each fix or new feature would be better to merge.

**Comment by aash** [comment]
@henricavalcante 
Why? What if I'm not going to merge it at all? :smile:

**Comment by highvoltz** [comment]
Closing this since it's outdated and I don't have time to go through all the changes.

**Pull request closed without merging**
